### ISSUE TITLE
Create conda package & make the tool available via Galaxy

### ISSUE THREAD

**Issue by hechth** [francescodc87/ipaPy2#1]
Hi! I came across your recent publication and I think this tool would be interesting for many people working with mass spectrometry data. For this, it would be really cool to embed it in the Galaxy ecosystem which allows running command line applications on a compute cluster for reproducible and open science. This would also greatly improve visibility for your tool and the related publication.

It would be great for people to have this package also available via one of the conda channels such as `bioconda` or `conda-forge` to reach a wider audience. This would also be the first step required to make the tool available via Galaxy.

Since this package is already on pypi, it will be easy to create the conda recipe via [grayskull](https://github.com/conda/grayskull) to contribute it to [conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html) or [bioconda](https://bioconda.github.io/contributor/index.html). As soon as the package is published via conda, it is quite straightforward to put it into Galaxy. I'm happy to help and contribute during the process, feel free to list me under the maintainers of the bioconda package together with one of the original package developers and to request me as a reviewer for the PRs.

For contributing Galaxy tools, there are training materials and guidelines available [here](https://training.galaxyproject.org/training-material/topics/dev/tutorials/tool-integration/slides.html) and the tool should be deposited [here](https://github.com/galaxyproject/tools-iuc). Please feel free to reach out to me via email or otherwise if you need any help!

**Comment by francescodc87** [comment]
Hi Helge,
This is a great suggestion, thanks. I put this on my to do list and I am taking up your offer to help :). I'll reach out by email soon.

**Comment by hechth** [comment]
@francescodc87 the conda package is there and I think the issue for the Galaxy tool we will move [here](https://github.com/RECETOX/galaxytools/issues/454) so I think this can be closed.
